#!/bin/sh

# An ugly script that we currently use to push Homebrew formulae over to
# GitHub. This should get integrated into our build scripts somehow.

set -e

# Get the existing formulae from Github.
git clone git@github.com:NuxiNL/homebrew-cloudabi.git
cd homebrew-cloudabi

# Throw away the existing ones and replace them by the latest versions
# generated by CloudABI Ports.
rm *unknown-cloudabi*.rb
cp /usr/local/www/nuxi.nl/public/distfiles/cloudabi-ports/homebrew/formulae/* .
git add .

# Commit and push.
git commit -a -m 'Sync in latest formulae from the CloudABI Ports Collection.' || true
git push
rm -Rf ../homebrew-cloudabi
